<div class="page-title">

    <h1><?php echo $this->__('Frequently Asked Questions') ?></h1>

</div>
<div class="block">
    <div class="block-title">
        <strong><span><?php echo $this->__('Add FAQ') ?></span></strong>
    </div>
    <div class="block-content">
    <form name="addfaq" id="addfaq" action="<?php echo Mage::getUrl('faq')?>index/addfaq" method="post">
<div class="fieldset">
        
        <ul class="form-list">
            <li class="fields">
            <div class="field">
            <label for="username"><?php echo $this->__('Name') ?> <span class="required">*</span></label>
        <input name="username" id="username" title="user name" value="" class="input-text required-entry" type="text" />
        </div>
        <div class="field">
        <label for="useremail"><?php echo $this->__('Email') ?> <span class="required">*</span></label>
        <input name="useremail" id="useremail" title="useremail" value="" class="input-text required-entry validate-email" type="text" /> 
        </div>
        </li>
        
        <?php $categories = $this->getCategoryCollection(); ?>
        <?php if(count($categories)): ?>
        <li class="fields">
        <div class="field">
        <label for="drp_category"><?php echo $this->__('Category') ?></label>
        <div class="faqinput-select">
        <select name="drp_category" id="drp_category">
        <?php             
            foreach($categories as $cat)
            {
                echo '<option value="'.$cat->getFaqCatId().'">'.$cat->getName().'</option>';
            } 
        ?>
            
        </select>
        </div>
        </div>
        </li>
        <?php endif; ?>
        
        <li class="wide">
        <div class="field">
        <label for="question"><?php echo $this->__('Question') ?> <span class="required">*</span></label>
        <input name="question" id="question" title="Question" value="" class="input-text required-entry" type="text" />
        </div>
        </li>
                </ul>
</div>
        <div class="buttons-set">
        <input type="submit" name="submit" value="<?php echo $this->__('Submit') ?>" />
        </div>
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
    </form>
    <script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('addfaq');
    //]]>
</script>
    </div>
</div>
